apiVersion: v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    name: test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: test-deployment
  template:
    metadata:
      labels:
        name: test-deployment
    spec:
      containers:
      - name: mohamedgalia/change
        image: mohamedgalia/change
        ports:
        - containerPort: 5000
      - name: mysql
        image: mysql
        ports:
        - containerPort: 3306
